### ISSUE TITLE
Problem with opening OneDrive

### ISSUE THREAD

**Issue by Philipp0205** [prrvchr/oneDriveOOo#1]
Hey there,
I followed every step of the installation in the ReadMe.

![image](https://user-images.githubusercontent.com/36603238/59562889-c3d82e00-9032-11e9-9a0e-c991b4e0654d.png)

In the last step I am changing the File name to the specified String, but nothing happens.
I am doing it right? 

Thanks!

**Comment by prrvchr** [comment]
Hi Philipp0205,

I guess you are on Windows, and I have to finish the logging implementation to be able to debug on this platform.
For the moment this application is functional only under Linux with OpenOffice or LibreOffice.

I come back to you, as soon as I advanced on the logging, it will be possible to identify more easily where the malfunctions are.
Thank you for taking the time to test, it helps me especially under Windows, because I really miss test platform under Windows

**Comment by Philipp0205** [comment]
I am current on Ubuntu 19.04.. Maybe I just have to reinstall everything and try again. Thanks for maintaining the extension!

**Comment by prrvchr** [comment]
Ok, if you are on Ubuntu, the easiest way to debug is to launch soffice from a terminal. (alt + F4, soffice + return).

In the terminal, you can see what the extension is doing.

**Comment by prrvchr** [comment]
Hi Philipp0205,

A new version [oneDriveOOo v0.0.5(https://github.com/prrvchr/oneDriveOOo/raw/master/oneDriveOOo.oxt)] is available.

Can you make tests with this new version and open a new issue if necessary.
